name: 'cargo test & clippy'
on:
  push:
    paths:
    - "**/Cargo.lock"
    - "**/Cargo.toml"
    - "**/*.rs"
  pull_request:
    paths:
    - "**/Cargo.lock"
    - "**/Cargo.toml"
    - "**/*.rs"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update &&\
          sudo apt-get install libusb-1.0-0-dev -y
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: '--all-features -- -D warnings'

